# Generated by Django 4.2.5 on 2023-09-28 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('option', models.CharField(verbose_name=10)),
                ('points', models.SmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='judge_awards',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='judging_closes',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='members_vote',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='open_for_judging',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='entries_close',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='open_for_entries',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='joined',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.competition')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.image')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.voteoption')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.member')),
            ],
        ),
    ]
