# Generated by Django 4.2.5 on 2023-09-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_voteoption_competition_judge_awards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='current',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='joined',
            field=models.DateField(blank=True, null=True),
        ),
    ]
