# Generated by Django 4.2.5 on 2023-10-02 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_competition_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='competition',
            name='description',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='name',
        ),
        migrations.AlterField(
            model_name='competition',
            name='images',
            field=models.ManyToManyField(blank=True, to='main.image'),
        ),
        migrations.AddField(
            model_name='competition',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.subject'),
            preserve_default=False,
        ),
    ]
