# Generated by Django 4.2.5 on 2023-10-02 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_competition_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='subject',
        ),
    ]
