# Generated by Django 4.2.5 on 2023-10-02 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_competition_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.subject'),
        ),
    ]
