# Generated by Django 4.2.5 on 2023-10-03 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_competition_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.judge'),
        ),
    ]
