# Generated by Django 4.2.5 on 2023-10-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_competition_judge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='rules',
        ),
        migrations.AddField(
            model_name='competitiontype',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='competitiontype',
            name='rules',
            field=models.ManyToManyField(to='main.rule'),
        ),
    ]
