# Generated by Django 4.2.5 on 2023-10-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_competition_rules_competitiontype_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
