# Generated by Django 4.2.5 on 2023-10-09 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_event_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Awarders',
            new_name='Awarder',
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['starts']},
        ),
    ]
