# Generated by Django 4.2.5 on 2023-10-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_awarders_awarder_alter_event_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='rules',
            field=models.ManyToManyField(blank=True, to='main.rule'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='competitions', to='main.image'),
        ),
    ]
