# Generated by Django 4.2.5 on 2023-10-22 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0015_remove_competition_rules'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rule',
            options={'ordering': ['description']},
        ),
        migrations.AlterField(
            model_name='image',
            name='print',
            field=models.BooleanField(default=False, verbose_name='Entered as a print'),
        ),
        migrations.AlterField(
            model_name='member',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
