# Generated by Django 4.2.5 on 2023-10-23 14:11

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_position_options_position_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blurb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('contents', tinymce.models.HTMLField()),
            ],
        ),
    ]
