# Generated by Django 4.2.5 on 2023-12-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_gallery_images_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteoption',
            name='judge_only',
            field=models.BooleanField(default=False),
        ),
    ]
