# Generated by Django 4.2.5 on 2024-01-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_voteoption_judge_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitiontype',
            name='contributes_to_annual',
            field=models.BooleanField(default=True),
        ),
    ]
