# Generated by Django 4.2.5 on 2024-01-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_competitiontype_contributes_to_annual'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteoption',
            name='exclusive',
            field=models.BooleanField(default=True),
        ),
    ]
