# Generated by Django 4.2.5 on 2024-01-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_voteoption_exclusive'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitiontype',
            name='selection_not_places',
            field=models.BooleanField(default=False),
        ),
    ]
