# Generated by Django 4.2.5 on 2024-02-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_competitiontype_selection_not_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='year',
            field=models.SmallIntegerField(null=True),
        ),
    ]
