# Generated by Django 4.2.5 on 2024-04-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_person_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='files/news/')),
            ],
        ),
        migrations.AlterField(
            model_name='competitiontype',
            name='rules',
            field=models.ManyToManyField(blank=True, to='main.rule'),
        ),
    ]
