# Generated by Django 4.2.5 on 2024-04-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_newsletter_alter_competitiontype_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='issue_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
