# Generated by Django 4.2.5 on 2024-04-10 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_newsletter_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 10, 22, 29, 41, 477199)),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='files/news/thumbnails/'),
        ),
    ]
