# Generated by Django 4.2.5 on 2024-04-20 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_newsletter_issue_date_alter_newsletter_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 20, 14, 13, 36, 30866)),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='files/news/thum'),
        ),
    ]
