# Generated by Django 4.2.5 on 2024-10-12 02:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_newsletter_issue_date_alter_newsletter_thumb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awardtype',
            options={'ordering': ['-points']},
        ),
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ['-event__starts']},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['title', 'author', 'print']},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['person__firstname']},
        ),
        migrations.AlterField(
            model_name='judge',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge', to='main.person'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 12, 10, 29, 3, 969780)),
        ),
    ]
